services:
  redis:
    image: redis:7
    container_name: re_l_redis
    command: >
      redis-server --requirepass ${REDIS_PASSWORD}

    env_file:
      - .env # â† use the same file Python loads
    ports: ["6379:6379"]
    volumes: ['redis_data:/data']
    restart: unless-stopped
volumes:
  redis_data:
